services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "27017:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: TFI
      MARIADB_USER: tfi
      MARIADB_PASSWORD: 1234
    networks:
      - tfi

volumes:
  mariadb:

networks:
  tfi:
    driver: bridge